CREATE DATABASE IF NOT EXISTS patient_history;
USE patient_history;


-- Patient Demographics Table
CREATE TABLE IF NOT EXISTS patientdemographics (
PatientID INT(11) NOT NULL AUTO_INCREMENT,
HospitalMRNo VARCHAR(50) DEFAULT NULL,
PtLastName VARCHAR(128) DEFAULT NULL,
PtPreviousLastName VARCHAR(128) DEFAULT NULL,
PtFirstName VARCHAR(128) DEFAULT NULL,
PtMiddleInitial VARCHAR(4) DEFAULT NULL,
Suffix VARCHAR(10) DEFAULT NULL,
HomeAddress VARCHAR(128) DEFAULT NULL,
HomeCity VARCHAR(128) DEFAULT NULL,
HomeStateProvinceRegion VARCHAR(50) DEFAULT NULL,
HomeZip VARCHAR(15) DEFAULT NULL,
Country VARCHAR(75) DEFAULT NULL,
Citizenship VARCHAR(75) DEFAULT NULL,
PtHomePhone VARCHAR(14) DEFAULT NULL,
EmergencyPhoneNumber VARCHAR(14) DEFAULT NULL,
EmailAddress VARCHAR(128) DEFAULT NULL,
SSN VARCHAR(12) DEFAULT NULL,
DOB DATETIME DEFAULT NULL,
Gender VARCHAR(50) DEFAULT NULL,
EthnicAssociation VARCHAR(75) DEFAULT NULL,
Religion VARCHAR(75) DEFAULT NULL,
MaritalStatus VARCHAR(25) DEFAULT NULL,
EmploymentStatus VARCHAR(50) DEFAULT NULL,
DateofExpire DATETIME DEFAULT NULL,
Referral VARCHAR(128) DEFAULT NULL,
CurrentPrimaryHCPId VARCHAR(128) DEFAULT NULL,
Comments VARCHAR(254) DEFAULT NULL,
DateEntered DATETIME DEFAULT NULL,
NextOfKinID VARCHAR(128) DEFAULT NULL,
NextOfKinRelationshipToPatient VARCHAR(50) DEFAULT NULL,
deleted TINYINT(1) DEFAULT 0,
PRIMARY KEY (PatientID),
KEY I_LastName (PtLastName),
KEY I_HomePhone (PtHomePhone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- Allergy History Table
CREATE TABLE IF NOT EXISTS allergyhistory (
AllergyID INT(11) NOT NULL AUTO_INCREMENT,
PatientID INT(11) DEFAULT NULL,
Allergen VARCHAR(254) DEFAULT NULL,
AllergyStartDate VARCHAR(25) DEFAULT NULL,
AllergyEndDate VARCHAR(25) DEFAULT NULL,
AllergyDescription VARCHAR(254) DEFAULT NULL,
deleted TINYINT(1) DEFAULT 0,
PRIMARY KEY (AllergyID),
KEY I_Allergy_PatientID (PatientID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- General Medical History Table
CREATE TABLE IF NOT EXISTS generalmedicalhistory (
GeneralMedicalHistoryID INT(11) NOT NULL AUTO_INCREMENT,
PatientID INT(11) DEFAULT NULL,
MaritalStatus VARCHAR(25) DEFAULT NULL,
Education VARCHAR(50) DEFAULT NULL,
BehavioralHistory VARCHAR(254) DEFAULT NULL,
Tobacco VARCHAR(50) DEFAULT NULL,
TobaccoQuantity VARCHAR(75) DEFAULT NULL,
TobaccoDuration VARCHAR(75) DEFAULT NULL,
Alcohol VARCHAR(50) DEFAULT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

